name: Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run deploy commands on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd ~/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2
          # Run all commands and save all output to a log file
          {
            echo "--- Setting PATH ---"
            export PATH=$PATH:/home/ec2-user/.local/bin
            echo "PATH is now: $PATH"
            echo "--- Killing old process ---"
            pkill -f "flask run" || echo "pkill failed or no process was running."
            echo "--- Installing dependencies ---"
            python3 -m pip install -r requirements.txt
            echo "--- Starting new process ---"
            nohup python3 -m flask run --host=0.0.0.0 --port=5000 &
            echo "--- Script finished ---"
          } > deploy_log.txt 2>&1

    - name: Download Debug Log from EC2
      if: always() # This makes the step run even if the previous one fails
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 22
        source: "~/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2/deploy_log.txt"
        target: "."

    - name: Display Debug Log
      if: always() # This also runs regardless of failure
      run: |
        echo "--- Contents of deploy_log.txt from the server ---"
        cat deploy_log.txt