name: Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd ~/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2 || git clone https://github.com/TechTyphoon/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2.git ~/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2
          cd ~/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2

          git pull origin main
          export PATH=$PATH:/home/ec2-user/.local/bin
          pkill -f "flask run" || true
          python3 -m pip install -r requirements.txt
          nohup python3 -m flask run --host=0.0.0.0 --port=5000 &