name: Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: echo "✅ SSH Connection Successful"

    - name: Copy files to EC2 via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        source: "app.py,requirements.txt,.github"
        target: "~/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2"

    - name: Run deploy commands on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          cd ~/CI-CD-Pipeline-for-a-Flask-App-on-AWS-EC2
          # Run all commands and save all output to a log file
          {
            echo "--- Setting PATH ---"
            export PATH=$PATH:/home/ec2-user/.local/bin
            echo "PATH is now: $PATH"
            echo "--- Killing old process ---"
            pkill -f "flask run" || echo "pkill failed or no process was running."
            echo "--- Installing dependencies ---"
            python3 -m pip install -r requirements.txt
            echo "--- Starting new process ---"
            nohup python3 -m flask run --host=0.0.0.0 --port=5000 &
            echo "--- Script finished ---"
          } > deploy_log.txt 2>&1
          # Print the contents of the log file to the GitHub Actions output
          cat deploy_log.txt
