name: Test EC2 Connection

on:
  push:
    branches:
      - main

jobs:
  test-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Run Simple Test Commands on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          echo "--- Test: Starting simple commands ---"
          echo "Hello from EC2!"
          echo "Current user is:"
          whoami
          echo "Current directory is:"
          pwd
          echo "--- Test finished ---"